### 必要配置

## 数据库
#SQLALCHEMY_DATABASE_URI: 'sqlite:///{{cookiecutter.project_slug}}.db'
## sentry服务
#sentry_dns: null


### 服务配置

## 可限制单次写入数量 0表示无限制
#insert_limit: 0
## 查询默认限制数量
#default_limit: 20

### 系统配置

#LOG_FORMAT: '[%(asctime)s] [%(uuid)s] [%(threadName)s:%(thread)d] [%(levelname)s]: %(message)s [%(pathname)s <%(lineno)d>]'
#LOG_LEVEL: "DEBUG"
#SECRET_KEY: ''
#SQLALCHEMY_TRACK_MODIFICATIONS: True
#SQLALCHEMY_ECHO: False
