name: Test
on: [ push, pull_request ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup package
        run: |
          pip install cookiecutter mock six 
          cookiecutter . --no-input

      - name: Install
        run: |
          pip install -r ./python-boilerplate/requirements.txt
          pip install -r ./python-boilerplate/requirements_dev.txt

      - name: test
        run: |
          cd ./python-boilerplate && python setup.py test

